//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::centres::Entity as Centres;
pub use super::contacts::Entity as Contacts;
pub use super::depots::Entity as Depots;
pub use super::famille_mtcs::Entity as FamilleMtcs;
pub use super::familles::Entity as Familles;
pub use super::letypes::Entity as Letypes;
pub use super::marque_oems::Entity as MarqueOems;
pub use super::marques::Entity as Marques;
pub use super::notes::Entity as Notes;
pub use super::users::Entity as Users;
